level: [2, 4, 6, 8, 10]

recto: ["ğŸ˜¯", "ğŸ˜€", "ğŸ˜", "ğŸ¤£", "ğŸ˜‰",
        "ğŸ˜", "ğŸ˜", "ğŸ¤—", "ğŸ¤©", "ğŸ˜‘",
        "ğŸ™„", "ğŸ˜£", "ğŸ˜", "ğŸ˜®", "ğŸ¤",
        "ğŸ˜«", "ğŸ˜´", "ğŸ˜›", "ğŸ¤¤", "ğŸ˜“",
        "ğŸ™ƒ", "ğŸ¤‘", "ğŸ¥µ", "ğŸ¥¶", "ğŸ˜¤",
        "ğŸ˜­", "ğŸ¥³", "ğŸ˜¨", "ğŸ¤¯", "ğŸ˜±",
        "ğŸ¤ª", "ğŸ˜µ", "ğŸ˜¡", "ğŸ¥º", "ğŸ˜·",
        "ğŸ¤•", "ğŸ¤¢", "ğŸ¤®", "ğŸ˜‡", "ğŸ¤ ",
        "ğŸ¤¥", "ğŸ§", "ğŸ˜ˆ", "ğŸ¤¡", "ğŸ‘»",
        "ğŸ¤˜", "ğŸ", "ğŸ¦†", "ğŸ¦", "ğŸ®"]

verso: "â“"

bdd: "database.json"
